# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 632eb4d30d184308410f170aa7aa249aa8ca243e1e57c878642bae586aab56ad20b58044eed30746a2283989ae61af0d35cc622e450c9630b4afb17457f379f0

test:
  secret_key_base: 644585465f0db8d494fa8742255ea67c8f5661df43efca9343fb458cc23bcc1a093834072288dcc6998b123ec3d24d65aa44e0156142df9dae264856f21e4dec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
